name: my_uz
description: Aplikacja do zarządzania planem zajęć UZ

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase:
  supabase_flutter:
  beautiful_soup_dart:
  http:
  html:
  icalendar_parser:
  intl:
  crypto:
  uuid:
  equatable:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true