name: MyUZ
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.9
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.3.4
  device_preview: ^1.1.0
  flutter_speed_dial:
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/logo_uz.png
    - .env

  fonts:
    - family: MyUzIcons
      fonts:
        - asset: fonts/MyUzIcons.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-Italic.ttf
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_uz.png"