name: my_uz
description: Aplikacja do zarządzania planem zajęć UZ

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Zaktualizowano do Flutter 3.x

dependencies:
  flutter:
    sdk: flutter
  http:   # Do pobierania plików ICS
  logger: # Do logowania
  supabase_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:   # Najnowsze linty

flutter:
  uses-material-design: true

# 🔴 Dodaj to dla skryptów w bin/
executables:
  scraper: scraper  # Umożliwia uruchomienie przez `dart run scraper`