/// Flutter icons MyUZicons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyUZicons
///      fonts:
///       - asset: fonts/MyUzIcons.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class MyUzIcons {
  MyUzIcons._();

  static const _kFontFam = 'MyUzIcons';
  static const String? _kFontPkg = null;

  static const IconData chevron_left_svgrepo_com = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right_svgrepo_com = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_01_svgrepo_com = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_01_svgrepo_com = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData palette_svgrepo_com = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_02_svgrepo_com = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_check = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation_hat = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_minus_02_svgrepo_com = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_open = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marker_pin = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_svgrepo_com = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
