name: Build Flutter iOS and Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        platform: [ios, android]
      fail-fast: false
      exclude:
        - os: ubuntu-latest
          platform: ios
        - os: macos-latest
          platform: android

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2'
          cache: true

      - name: Clean & install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Build iOS
        if: matrix.platform == 'ios'
        run: flutter build ipa --export-options-plist=ios/ExportOptions.plist

      - name: Upload IPA
        if: matrix.platform == 'ios'
        uses: actions/upload-artifact@v4
        with:
          name: iOS-IPA
          path: build/ios/ipa/*.ipa

      - name: Build Android
        if: matrix.platform == 'android'
        run: flutter build apk --release

      - name: Upload APK
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk