name: Build and Release

on:
  push:
    branches: [ main ]
  # Można też dodać manualny trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Setup Dart SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
          sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
          sudo apt-get update
          sudo apt-get install dart=3.5.0-1

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
      # Kolejne kroki - upload artefaktów, itp.