name: Run Scraper (manual)

on:
  workflow_dispatch:
    inputs:
      verbose:
        description: "Wypisz dodatkowe informacje (logger DEBUG)"
        required: false
        default: "false"
      dry_run:
        description: "Nie zapisuj do bazy (NA PRZYSZŁOŚĆ)"
        required: false
        default: "false"

# (opcjonalnie – odkomentuj gdy będziesz chciała harmonogram)
# schedule:
#   - cron: '0 3 * * *'  # codziennie 03:00 UTC

jobs:
  scrape:
    name: Uruchom scraper
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: scraper-manual
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ustaw Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: scraper/requirements.txt

      - name: Instalacja zależności
        run: |
          pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Weryfikacja zmiennych środowiskowych
        run: |
          test -n "${SUPABASE_URL}" || (echo 'Brak SUPABASE_URL' && exit 1)
          test -n "${SUPABASE_SERVICE_ROLE_KEY}" || (echo 'Brak SUPABASE_SERVICE_ROLE_KEY' && exit 1)
          echo "✔ Zmienne środowiskowe obecne"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Uruchom scraper
        id: run_scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          VERBOSE: ${{ github.event.inputs.verbose }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        run: |
          echo "== Start ==" | tee scraper_run.log
          python -m scraper.main 2>&1 | tee -a scraper_run.log
          echo "== Koniec ==" | tee -a scraper_run.log

      - name: Artefakt logów
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: scraper-logs
          path: scraper_run.log
          retention-days: 7

      - name: Krótki podsumowujący log
        if: always()
        run: |
          echo "Run zakończony statusem: ${{ job.status }}"

