name: Plan UZ Scraper

on:
  schedule:
    # Uruchamia się codziennie o 3:00 w nocy (UTC)
    - cron: '0 3 * * *'
  workflow_dispatch:
  # Umożliwia ręczne uruchomienie z konsoli GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python scraper/main.py