name: Run Scraper

on:
  schedule:
    - cron: '0 4 * * *'  # Codziennie o 4:00 rano UTC
  workflow_dispatch:     # Pozwala na ręczne uruchomienie

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Run scraper
        run: dart lib/scraper/main.dart  # Ścieżka do Twojego skryptu scrapera
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}